### ISSUE TITLE
Current bosh.io release does not include ntpd_server

### ISSUE THREAD

**Issue by sharms** [cloudfoundry-community/ntp-release#3]
Using the repo, it appears there are two jobs: `ntpd` and `ntpd_server`.  The current bosh.io published release only has `ntpd` which leads to confusion.

https://github.com/cloudfoundry-community/ntp-release/blob/master/jobs/ntpd_server/spec
http://bosh.io/releases/github.com/cloudfoundry-community/ntp-release?version=4

**Comment by cunnie** [comment]
I'm closing this issue; I haven't been maintaining this release for > 5 years, so this repo should be considered "orphaned". Sorry.
